from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path


def parse_yaml_utf8(validate_module, path: Path):
    text = path.read_text(encoding="utf-8")
    parser = validate_module.SimpleYamlParser(text)
    return parser.parse()


def load_validate_module(project_root: Path):
    validate_path = project_root / "scripts" / "validate_data.py"
    spec = importlib.util.spec_from_file_location("validate_data", validate_path)
    if spec is None or spec.loader is None:
      raise RuntimeError("無法載入 validate_data.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def build_trip_data(project_root: Path) -> dict:
    validate_module = load_validate_module(project_root)
    data_dir = project_root / "data"

    itinerary_raw = parse_yaml_utf8(validate_module, data_dir / "itinerary.yaml")
    restaurants_raw = parse_yaml_utf8(validate_module, data_dir / "restaurants.yaml")
    places_raw = parse_yaml_utf8(validate_module, data_dir / "places.yaml")
    transportation_raw = parse_yaml_utf8(validate_module, data_dir / "transportation.yaml")

    project = itinerary_raw["project"]

    return {
        "project": {
            "name": project["name"],
            "language": project["language"],
            "startDate": project["start_date"].replace("-", "/"),
            "endDate": project["end_date"].replace("-", "/"),
            "routeFocus": project["route_focus"],
            "version": project["version"],
            "status": project["status"],
        },
        "days": itinerary_raw["itinerary"],
        "restaurants": restaurants_raw["restaurants"],
        "places": places_raw["places"],
        "transportation": transportation_raw["transportation"],
    }


def write_data_js(output_path: Path, payload: dict) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    js = (
        "// Generated by scripts/build_web_data.py. Do not edit manually.\n"
        f"window.TRIP_DATA = {json.dumps(payload, ensure_ascii=False, indent=2)};\n"
    )
    output_path.write_text(js, encoding="utf-8")


def main() -> int:
    project_root = Path(__file__).resolve().parents[1]
    payload = build_trip_data(project_root)
    output_paths = [
        project_root / "web" / "data.js",
        project_root / "docs" / "data.js",
    ]
    for output_path in output_paths:
        write_data_js(output_path, payload)
        print(f"已產生 {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
